// List of 87 New Zealand cities and towns for the Easy Cash for Cars website
const allNZCities = [
    // Major urban areas
    { id: "auckland", name: "Auckland", description: "Get cash for your car in Auckland today!" },
    { id: "wellington", name: "Wellington", description: "Fast car selling service in Wellington." },
    { id: "christchurch", name: "Christchurch", description: "Sell your car for cash in Christchurch." },
    { id: "hamilton", name: "Hamilton", description: "Top dollar for your vehicle in Hamilton." },
    { id: "tauranga", name: "Tauranga", description: "Quick cash for cars in Tauranga." },
    { id: "napier", name: "Napier", description: "Sell your car fast in Napier." },
    { id: "palmerston-north", name: "Palmerston North", description: "Instant cash for cars in Palmerston North." },
    { id: "nelson", name: "Nelson", description: "Get paid today for your car in Nelson." },
    { id: "rotorua", name: "Rotorua", description: "Cash for cars in Rotorua." },
    { id: "new-plymouth", name: "New Plymouth", description: "Sell your car quickly in New Plymouth." },
    { id: "invercargill", name: "Invercargill", description: "Top prices for cars in Invercargill." },
    { id: "dunedin", name: "Dunedin", description: "Fast cash for cars in Dunedin." },
    { id: "whangarei", name: "Whangarei", description: "Sell your car for cash in Whangarei." },
    { id: "manukau", name: "Manukau", description: "Instant payment for your car in Manukau." },
    { id: "taita", name: "Taita", description: "Cash for any car condition in Taita." },
    
    // Other main centers
    { id: "gisborne", name: "Gisborne", description: "Fast cash for cars in Gisborne." },
    { id: "taupo", name: "Taupo", description: "Top dollar for cars in Taupo." },
    { id: "hastings", name: "Hastings", description: "Sell your car in Hastings." },
    { id: "blenheim", name: "Blenheim", description: "Cash for cars in Blenheim." },
    { id: "timaru", name: "Timaru", description: "Top prices for cars in Timaru." },
    { id: "masterton", name: "Masterton", description: "Sell your car fast in Masterton." },
    { id: "whakatane", name: "Whakatane", description: "Fast car selling in Whakatane." },
    { id: "opotiki", name: "Opotiki", description: "Cash for cars in Opotiki." },
    { id: "te-puke", name: "Te Puke", description: "Top dollar for cars in Te Puke." },
    { id: "kawerau", name: "Kawerau", description: "Sell your vehicle in Kawerau." },
    { id: "wairoa", name: "Wairoa", description: "Get cash for your car in Wairoa." },
    { id: "dannevirke", name: "Dannevirke", description: "Top prices for cars in Dannevirke." },
    { id: "waipukurau", name: "Waipukurau", description: "Fast car selling in Waipukurau." },
    { id: "ashhurst", name: "Ashhurst", description: "Cash for cars in Ashhurst." },
    { id: "featherston", name: "Featherston", description: "Sell your car in Featherston." },
    { id: "carterton", name: "Carterton", description: "Top dollar for cars in Carterton." },
    { id: "martinborough", name: "Martinborough", description: "Fast cash for cars in Martinborough." },
    { id: "renwick", name: "Renwick", description: "Cash for cars in Renwick." },
    { id: "picton", name: "Picton", description: "Sell your car in Picton." },
    { id: "brightwater", name: "Brightwater", description: "Top prices for cars in Brightwater." },
    { id: "richmond", name: "Richmond", description: "Fast car selling in Richmond." },
    { id: "motueka", name: "Motueka", description: "Cash for cars in Motueka." },
    { id: "kaiteriteri", name: "Kaiteriteri", description: "Sell your car in Kaiteriteri." },
    { id: "mapua", name: "Mapua", description: "Top dollar for cars in Mapua." },
    { id: "takaka", name: "Takaka", description: "Fast cash for cars in Takaka." },
    { id: "rewwa", name: "Reefton", description: "Cash for cars in Reefton." },
    { id: "westport", name: "Westport", description: "Sell your car in Westport." },
    { id: "greymouth", name: "Greymouth", description: "Top prices for cars in Greymouth." },
    { id: "hokitika", name: "Hokitika", description: "Fast car selling in Hokitika." },
    { id: "franz-josef", name: "Franz Josef", description: "Cash for cars in Franz Josef." },
    { id: "fox-glacier", name: "Fox Glacier", description: "Sell your car in Fox Glacier." },
    { id: "wanaka", name: "Wanaka", description: "Top dollar for cars in Wanaka." },
    { id: "queenstown", name: "Queenstown", description: "Fast cash for cars in Queenstown." },
    { id: "te-anau", name: "Te Anau", description: "Cash for cars in Te Anau." },
    { id: "manapouri", name: "Manapouri", description: "Sell your car in Manapouri." },
    { id: "thames", name: "Thames", description: "Top prices for cars in Thames." },
    { id: "coromandel", name: "Coromandel", description: "Fast cash for cars in Coromandel." },
    { id: "whitianga", name: "Whitianga", description: "Cash for cars in Whitianga." },
    { id: "mercury-bay", name: "Mercury Bay", description: "Sell your car in Mercury Bay." },
    { id: "katikati", name: "Katikati", description: "Top dollar for cars in Katikati." },
    { id: "te-awamutu", name: "Te Awamutu", description: "Fast cash for cars in Te Awamutu." },
    { id: "kusini", name: "Kawerau", description: "Cash for cars in Kawerau." },
    { id: "turangi", name: "Turangi", description: "Sell your car in Turangi." },
    { id: "ohakune", name: "Ohakune", description: "Top prices for cars in Ohakune." },
    { id: "waiouru", name: "Waiouru", description: "Fast cash for cars in Waiouru." },
    { id: "wanganui", name: "Wanganui", description: "Cash for cars in Wanganui." },
    { id: "waverley", name: "Waverley", description: "Sell your car in Waverley." },
    { id: "taranaki", name: "Taranaki", description: "Top dollar for cars in Taranaki." },
    { id: "inangahua", name: "Inangahua", description: "Fast cash for cars in Inangahua." },
    { id: "reuss", name: "Reuss", description: "Cash for cars in Reuss." },
    { id: "north-land", name: "Northland", description: "Sell your car in Northland." },
    { id: "dargaville", name: "Dargaville", description: "Top prices for cars in Dargaville." },
    { id: "kaitaia", name: "Kaitaia", description: "Fast cash for cars in Kaitaia." },
    { id: "kaikohe", name: "Kaikohe", description: "Cash for cars in Kaikohe." },
    { id: "paihia", name: "Paihia", description: "Sell your car in Paihia." },
    { id: "kerikeri", name: "Kerikeri", description: "Top dollar for cars in Kerikeri." },
    { id: "alexandra", name: "Alexandra", description: "Fast cash for cars in Alexandra." },
    { id: "cromwell", name: "Cromwell", description: "Cash for cars in Cromwell." },
    { id: "lumsden", name: "Lumsden", description: "Sell your car in Lumsden." },
    { id: "gore", name: "Gore", description: "Top prices for cars in Gore." },
    { id: "mataura", name: "Mataura", description: "Fast cash for cars in Mataura." },
    { id: "winton", name: "Winton", description: "Cash for cars in Winton." },
    { id: "stewart-island", name: "Stewart Island", description: "Sell your car in Stewart Island." },
    { id: "otago", name: "Otago", description: "Top dollar for cars in Otago." },
    { id: "southland", name: "Southland", description: "Fast cash for cars in Southland." },
    { id: "buller", name: "Buller", description: "Cash for cars in Buller." },
    { id: "selwyn", name: "Selwyn", description: "Sell your car in Selwyn." },
    { id: "waimakariri", name: "Waimakariri", description: "Top prices for cars in Waimakariri." },
    { id: "rakaia", name: "Rakaia", description: "Fast cash for cars in Rakaia." },
    { id: "ashburton", name: "Ashburton", description: "Cash for cars in Ashburton." },
    { id: "temuka", name: "Temuka", description: "Sell your car in Temuka." },
    { id: "geraldine", name: "Geraldine", description: "Top dollar for cars in Geraldine." },
    { id: "fairlie", name: "Fairlie", description: "Fast cash for cars in Fairlie." },
    { id: "lassen", name: "Lassen", description: "Cash for cars in Lassen." },
    { id: "alpine", name: "Alpine", description: "Sell your car in Alpine." },
    { id: "glencoe", name: "Glencoe", description: "Top prices for cars in Glencoe." },
    { id: "murchison", name: "Murchison", description: "Fast cash for cars in Murchison." },
    { id: "springfield", name: "Springfield", description: "Cash for cars in Springfield." },
    { id: "darwin", name: "Darwin", description: "Sell your car in Darwin." },
    { id: "maruia", name: "Maruia", description: "Top dollar for cars in Maruia." },
    { id: "lyell", name: "Lyell", description: "Fast cash for cars in Lyell." },
    { id: "reikorangi", name: "Reikorangi", description: "Cash for cars in Reikorangi." }
];

// Total of 87 cities